# Pylint: CI file modification for error code check - 1.

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -24,13 +24,6 @@ pipelines:
           - uname -a
           
           - python --version
-          
-          - pip install -r requirements.txt
-          
-          #- python -m unittest discover tests/
-          - python -m unittest FileAnalysis_UnitTest.py
-          
-          - python -m pylint SourceCodeChecker.py --rcfile=pylintrc
 
           # TODO: Review
           #- cd $BITBUCKET_CLONE_DIR
@@ -39,3 +32,24 @@ pipelines:
           # Win: cd
           - ls
 
+          - pip install -r requirements.txt
+          
+          #- python -m unittest discover tests/
+          - python -m unittest FileAnalysis_UnitTest.py
+          
+          #- python -m pylint SourceCodeChecker.py --rcfile=pylintrc
+          - python -m pylint SourceCodeChecker.py --rcfile=pylintrc
+          - PYLINT_EXIT_CODE=$?
+          # https://docs.pylint.org/en/1.6.0/run.html
+          # 1 - fatal, 2 - error, ..., 32 - usage
+
+            if [ $PYLINT_EXIT_CODE == 1 ] || [ $PYLINT_EXIT_CODE == 2 ] || [ $PYLINT_EXIT_CODE == 32 ]
+            then
+              echo 'Pylint exited with important error code'
+              echo $PYLINT_EXIT_CODE
+              exit 1
+            else
+              echo 'Pylint exited with ok / small error code'
+              echo $PYLINT_EXIT_CODE
+              exit 0
+            fi
